### ISSUE TITLE
Incompatible with current Android M Preview

### ISSUE THREAD

**Issue by KNGP14** [javiersantos/WhatsAppBetaUpdater.Android#6]
I've checked out the compatibility on my Nexus 5 running Android M Preview MPZ44Q.
It hasn't to be a real issue because of the current preview state of Android M but maybe there is a little code snippet that's not compatible with future Android releases.

Logcat output:
```
06-01 15:24:48.750    4945-4945/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.javiersantos.whatsappbetaupdater, PID: 4945
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.javiersantos.whatsappbetaupdater/md59c7d171be2c3fa8785b4ded0570f618e.MainActivity}: java.lang.UnsupportedOperationException: Use StringFactory instead.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5401)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
     Caused by: java.lang.UnsupportedOperationException: Use StringFactory instead.
            at java.lang.String.<init>(String.java:245)
            at md59c7d171be2c3fa8785b4ded0570f618e.MainActivity.n_onCreate(Native Method)
            at md59c7d171be2c3fa8785b4ded0570f618e.MainActivity.onCreate(MainActivity.java:32)
            at android.app.Activity.performCreate(Activity.java:6116)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5401)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
```

**Comment by KNGP14** [comment]
It will be fixed by the next preview build.
https://code.google.com/p/android-developer-preview/issues/detail?id=2073

**Comment by javiersantos** [comment]
Thanks for letting me know.
